name: Publish OSS Builds to S3
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to publish'
        required: false

jobs:
  publish:
    runs-on: ubuntu-latest
    name: Gradle Build and Publish
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Zulu JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Set CONDUCTOR_VERSION
        run: export CONDUCTOR_VERSION = ${{ github.event.inputs.version }}
      - name: Publish snapshot build
        run:  |
          ./gradlew properties --no-daemon --console=plain -q | grep "^version:" | awk '{printf $2}'
          echo "\nCONDUCTOR_VERSION env var is '$CONDUCTOR_VERSION'\n"
          ./gradlew publish -x test
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Publish release
        if: startsWith(github.ref, 'refs/tags/v') && (!contains(github.ref, '-rc.'))
        run: ./gradlew publish -x test
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
